CREATE DATABASE casestudy

USE casestudy

SELECT * FROM Product
SELECT * FROM Location
SELECT * FROM fact

---1. Display the number of states present in the LocationTable

SELECT COUNT(DISTINCT State) no_of_states FROM Location

---2. How many products are of regular type?

SELECT COUNT(Type) regular_type FROM Product
WHERE Type = 'Regular'

---3. How much spending has been done on marketing of product ID 1?

SELECT SUM(Total_Expenses) total_exp_prod1 FROM fact
WHERE ProductId = 1

---4. What is the minimum sales of a product?

SELECT MIN(sales) min_prod_sales FROM fact

---5. Display the max Cost of Good Sold (COGS)

SELECT MAX(COGS) max_cogs FROM fact

---6. Display the details of the product where product type is coffee

SELECT * FROM Product
WHERE Product_Type='Coffee'

---7. Display the details where total expenses are greater than 40.

SELECT * FROM fact
WHERE Total_Expenses>40
ORDER BY Total_Expenses

---8. What is the average sales in area code 719?

SELECT AVG(Sales) AvgSales_Area719 FROM fact
WHERE Area_Code = 719

---9. Find out the total profit generated by Colorado state

SELECT SUM(Profit) Colorado_Profits 
FROM fact f
JOIN Location l
On l.Area_Code = f.Area_Code
WHERE l.State='Colorado'

---CROSS CHECK:
SELECT Area_Code 
FROM Location 
WHERE State = 'Colorado'

SELECT SUM(Profit) FROM fact
WHERE Area_Code IN (303, 719, 720, 970)

---10. Display the average inventory for each product ID.

SELECT ProductId, AVG(Inventory) avg_inventory FROM fact
GROUP BY ProductId
ORDER BY ProductId

---11. Display state in a sequential order in a Location Table.

SELECT State From Location
ORDER BY State 

---12. Display the average budget of the Product where the average budget margin should be greater than 100.

SELECT ProductId, AVG(Budget_Margin) Product_AvgBudget
FROM fact
GROUP BY ProductId
HAVING AVG(Budget_Margin)>100

---13. What is the total sales done on date 2010-01-01?

SELECT SUM(Sales) Jan01_2010_Sales FROM fact
WHERE [Date] = '2010-01-01'

---14. Display the average total expense of each product ID on an individual date

SELECT ProductId, [Date], AVG(Total_Expenses) avg_prod_expense
FROM fact
GROUP BY ProductId, [Date]
ORDER BY ProductId, [Date]

---15. Display the table with the following attributes such as date, productID, product_type, product, sales, profit, state, area_code.

SELECT f.ProductId, f.[Date], p.Product_Type, p.Product, f.Sales, f.Profit, l.State, f.Area_Code 
FROM fact f
INNER JOIN Product p ON f.ProductId = p.ProductId
INNER JOIN Location l ON l.Area_Code = f.Area_Code
ORDER BY ProductId

---16. Display the rank without any gap to show the sales wise rank.

SELECT ProductId, Sales, 
DENSE_RANK() OVER (ORDER BY Sales DESC) AS SalesRank
FROM fact

---17. Find the state wise profit and sales.

SELECT l.State, SUM(f.Profit) total_profit, SUM(f.Sales) total_sales
FROM fact f
INNER JOIN Location l
ON f.Area_Code = l.Area_Code
GROUP BY l.State

---18. Find the state wise profit and sales along with the productname.

SELECT l.State, p.Product, SUM(f.Profit) total_profit, SUM(f.Sales) total_sales
FROM fact f
INNER JOIN Location l ON f.Area_Code = l.Area_Code
INNER JOIN Product p ON f.ProductId = p.ProductId
GROUP BY l.State, p.Product

---19. If there is an increase in sales of 5%, calculate the increasedsales.

CREATE FUNCTION get_increase_sales()
RETURNS TABLE
AS 
RETURN
(
  SELECT ProductId, Sales, Sales*1.05 AS increased_sales   --->increased_sales = Sales + Sales*0.05 = Sales*1.05
  FROM fact
)

SELECT * FROM get_increase_sales()

---20. Find the maximum profit along with the product ID and product type.

SELECT f.ProductId, p.Product_Type, MAX(Profit) max_product_profit 
FROM fact f
INNER JOIN Product p
ON f.ProductId = p.ProductID
GROUP BY p.Product_Type, f.ProductId

---21. Create a stored procedure to fetch the result according to the product type from Product Table.

CREATE PROCEDURE get_prod_deets(@Prod_type VARCHAR(20))
AS  
 SELECT * FROM Product
 WHERE Product_Type = @Prod_type
GO;

--CHECK PROCEDURE RESULT
EXEC get_prod_deets 'Herbal Tea'

---22. Write a query by creating a condition in which if the total expenses is less than 60 then it is a profit or else loss.

SELECT Total_Expenses, CASE
    WHEN Total_Expenses<60 THEN 'Loss' 
    ELSE 'Profit'
END AS [Profit/Loss]
FROM fact

---23. Give the total weekly sales value with the date and product ID details. Useroll-up to pull the data in hierarchical order.

SELECT DATEPART(YEAR, [Date]) [Year], 
       DATEPART(WEEK, [Date]) Week_no, 
       SUM(Sales) weekly_sales 
FROM fact
GROUP BY ROLLUP (DATEPART(YEAR, [Date]), DATEPART(WEEK, [Date]))
ORDER BY DATEPART(YEAR, [Date]), DATEPART(WEEK, [Date])

---24. Apply union and intersection operator on the tables which consist of attribute area code.

SELECT * FROM fact
UNION 
SELECT * FROM Location
-- cannot apply UNION, INTERSECT and EXCEPT on tables with unequal no. of columns hence this query throws error

---25. Create a user-defined function for the product table to fetch a particular product type based upon the user’s preference.

CREATE FUNCTION get_prods(@Product_Type VARCHAR(50))
RETURNS TABLE
AS
RETURN
  (SELECT * FROM Product
  WHERE Product_Type = @Product_Type)

SELECT * FROM get_prods('Coffee')

---26. Change the product type from coffee to tea where product ID is 1 and undo it

BEGIN TRANSACTION 
  UPDATE Product
  SET Product_Type = 'Tea' 
  WHERE ProductId = 1

  -- CHECK UPDATE:
  SELECT ProductId, Product_Type FROM Product WHERE ProductId = 1

ROLLBACK TRANSACTION

-- CROSS CHECK ROLLBACK:
SELECT ProductId, Product_Type FROM Product WHERE ProductId = 1

---27. Display the date, product ID and sales where total expenses are between 100 to 200.

SELECT [Date], ProductId, Sales, Total_Expenses FROM fact
WHERE Total_Expenses BETWEEN 100 AND 200

---28. Delete the records in the Product Table for regular type
DELETE FROM Product
WHERE Type='Regular'

---29. Display the ASCII value of the fifth character from the columnProduct.

SELECT Product, SUBSTRING(Product,5,1) as fifth_char, ASCII(SUBSTRING(Product,5,1)) fifth_char_ascii FROM Product